---
# tasks file for roles/user_create
#- name: Add Demo Group
#  group:
#    name: demo
#    state: present

- name: Add User to Demo Group
  user:
    name: "{{ user_name }}"
    shell: /bin/bash
    groups: 
      - wheel
    append: yes
    state: present